// AUTO-GENERATED by silicaflux_bitcoin.vectors.generate_vectors -- DO NOT EDIT.
// Single multi-core search scenario for tb/system/tb_hash_core_array.sv.
`define HCA_NUM_CORES 32'h00000004
`define HCA_BLOCK1 512'ha6c3d4dc08ed8bad88b88f348363ea72978e94d8aa9adf50d59dc0e9b13f7e206edb1df7b246eb2eb11b26c3a4d31d3bfbc708dff5d411fe76ac714fe3e9ef1a
`define HCA_TAIL3 96'h175bd4fa4aa18cbb89c966c2
`define HCA_NONCE_START 32'h179fab00
`define HCA_NONCE_STRIDE 32'h00000001
`define HCA_TARGET 256'h07ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
`define HCA_FOUND_CORE_ID 32'h00000001
`define HCA_FOUND_NONCE 32'h179fab01
`define HCA_FOUND_HASH 256'h22248c9c3abc828faa4185e3a7049753551855ae4bdc7c6acaf7ac367c9dd102
`define HCA_EXPECTED_HASHES_COMPLETED 32'h00000004
