// AUTO-GENERATED by silicaflux_bitcoin.vectors.generate_vectors -- DO NOT EDIT.
// `include`d by tb/unit testbenches to size vector arrays exactly to
// what generate_vectors.py actually wrote this run.
`define CH_MAJ_N 5008
`define SIGMA_N 5008
`define SCHEDULE_NBLOCKS 40
`define ROUND_N 5192
`define COMPRESSOR_N 3953
`define DOUBLE_HASH_N 801
`define NBITS_EXPAND_N 157
`define TARGET_COMPARE_N 154
`define HASH_CORE_N 6
