[package]
name = "web3emu-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "web3emu"
path = "src/main.rs"

[dependencies]
web3emu-types.workspace = true
web3emu-crypto.workspace = true
web3emu-account.workspace = true
web3emu-state.workspace = true
web3emu-tx.workspace = true
web3emu-trace.workspace = true
web3emu-contract.workspace = true
web3emu-execution.workspace = true
web3emu-block.workspace = true
web3emu-wallet.workspace = true
web3emu-core.workspace = true
web3emu-rpc.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
hex.workspace = true
